config/routes.rb
StudioSite::Application.routes.draw do
  get "term_library/show_styles"

  get "term_library/show_federations"

  get "term_library/show_term_groups"

  get "term_library/show_terms"

  get "web_services/studios"
  get "web_services/studio"
  get "web_services/events"
  get "web_services/repeating_events"
  get "web_services/terminology"

  match '/events/choose',  :to => 'events#choose'

  resources :repeating_events
  resources :events

  get "calendar/index"

  get "master_data/show_styles"
  get "master_data/show_federations"
  get "master_data/show_term_groups"
  get "master_data/show_terms"
  get "master_data/copy_terms"
  
  resources :master_data

  get "sessions/new"
  
  match ':controller/:action/:id.:format'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  match '/signup',  :to => 'studios#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  resources :studios
  match '/studio_images/:id', :to => 'studios#image', :as => :studio_image
  match '/term_images/:id', :to => 'terms#image', :as => :term_image
  
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :styles#,      :only => [:create, :destroy, :get]
  resources :term_groups#, :only => [:create, :destroy, :get]
  resources :terms#,       :only => [:create, :destroy]

  root :to => 'pages#home'

end

app/models/term_group.rb
class TermGroup < ActiveRecord::Base
  attr_accessible :name, :name_translated, :phonetic_spelling

  belongs_to :style
  has_many :terms, :dependent => :destroy

  validates :name,      :presence => true, :length => { :maximum => 250 }
  validates :style_id,  :presence => true

  default_scope :order => 'term_groups.name'
  
  def as_json(options={ })
    puts "TERM GROUP IS BEING CHECKED NOW"
    super({ :include => [:terms] }.merge(options))
  end  
end
# == Schema Information
#
# Table name: term_groups
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  style_id          :integer
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  phonetic_spelling :string(255)
#  name_translated   :string(255)
#

app/controllers/term_groups_controller.rb
class TermGroupsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy, :new, :update]
  
  def new
    @title = "Add Term Group"
    @current_style = Style.find(:first, :conditions => ["id = ? and studio_id = ?", current_style_id, params[:id]])
    
    @term_group = TermGroup.new
  end
  
  def create
    style = Style.find(current_style_id)
    @term_group = style.term_groups.build(params[:term_group])
    if @term_group.save
      flash[:success] = "Term group created"
      redirect_to :controller => :studios, :action => :show, :id => style.studio.id, :style_id => current_style_id
    else
      render 'pages/home'
    end
  end

  def edit
    @term_group = TermGroup.find(params[:id])
    @title = "Edit #{@term_group.name}"
    @term_groups = @term_group.style.term_groups
    @selected_term_group_id = @term_group.id
  end

  def update
    term_group = TermGroup.find(params[:id])
    if term_group.update_attributes(params[:term_group])
      flash[:success] = "Group saved"
      redirect_to :controller => :studios, :action => :show, :id => term_group.style.studio.id, :style_id => term_group.style.id
    end
  end
  

  def destroy
    term_group = TermGroup.find(params[:id])
    term_group.destroy
    flash[:success] = "Studio destroyed."
    redirect_to :controller => :studios, :action => :show, :id => term_group.style.studio.id, :style_id => term_group.style.id
  end
  
  def show
    @term_group = TermGroup.find(params[:id])
    respond_to do |format|
      format.json { render :json => @term_group.terms }
    end

  end
end

app/helpers/term_groups_helper.rb
module TermGroupsHelper
end

app/views/term_groups/_show.html.erb
<div class="term_group round">
   <span class="term_group_name">
      <% if can_edit_studio %>
         <%= link_to term_group.name, edit_term_group_path(term_group) %> 
      <% else %>
         <%= term_group.name %> 
      <% end %>
   </span>
   <% unless term_group.name_translated.nil? or term_group.name_translated.empty? %>
      &nbsp;==&nbsp;
      <span class="term_group_name_translated">
        <%= term_group.name_translated %> 
      </span>
   <% end %>
   <% if can_edit_studio %>
      [<%= link_to "+", master_data_show_styles_path(:target_term_group_id => term_group.id) %>]
      [<%= link_to "X", 
              term_group, 
              :method => :delete, 
              :confirm => "Are you sure you want to delete #{term_group.name}?",
              :title => "Delete #{term_group.name}" %>]
  <% end %>
   

   <% if term_group.terms.nil? or term_group.terms.count == 0 %>
      <br/>
   <% else %>
      <ul id="sortable_terms">
         <%= render :partial => "terms/show", :collection => term_group.terms, :as => :term %>
      </ul>
   <% end %>
   <%= link_to_if can_edit_studio, 'Add new term', new_term_path(:term_group_id => term_group.id, :style_id => term_group.style.id, :studio_id => term_group.style.studio.id), :class => 'term_group_add_term' %>
</div>
<br />

app/views/term_groups/_term_group_form.html.erb
   <%= form_for @term_group do |f| %>
     <%= render 'shared/error_messages', :object => f.object %>
     <div class="label">
      New Term Group:
     </div>
     <div class="field">
       <% if Rails.env.development? and @term_group.name.nil? %>
         <%= f.text_field :name, :value => Faker::Lorem.words().first %>
       <% else %>
         <%= f.text_field :name %>
       <% end %>
     </div>
     <div class="label">
      Translation:
     </div>
     <div class="field">
       <% if Rails.env.development? and @term_group.name_translated.nil? %>
         <%= f.text_field :name_translated, :value => Faker::Lorem.words().first %>
       <% else %>
         <%= f.text_field :name_translated %>
       <% end %>
     </div>
     
     
     <div class="actions">
       <%= f.submit "Submit" %>
     </div>
   <% end %>

   

app/views/term_groups/create.html.erb
<h1>TermGroups#create</h1>
<p>Find me in app/views/term_groups/create.html.erb</p>

app/views/term_groups/edit.html.erb
<%= render 'term_group_form' %>

app/views/term_groups/new.html.erb
<%= render 'term_group_form' %>