config/routes.rb
StudioSite::Application.routes.draw do
  get "term_library/show_styles"

  get "term_library/show_federations"

  get "term_library/show_term_groups"

  get "term_library/show_terms"

  get "web_services/studios"
  get "web_services/studio"
  get "web_services/events"
  get "web_services/repeating_events"
  get "web_services/terminology"

  match '/events/choose',  :to => 'events#choose'

  resources :repeating_events
  resources :events

  get "calendar/index"

  get "master_data/show_styles"
  get "master_data/show_federations"
  get "master_data/show_term_groups"
  get "master_data/show_terms"
  get "master_data/copy_terms"
  
  resources :master_data

  get "sessions/new"
  
  match ':controller/:action/:id.:format'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  match '/signup',  :to => 'studios#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  resources :studios
  match '/studio_images/:id', :to => 'studios#image', :as => :studio_image
  match '/term_images/:id', :to => 'terms#image', :as => :term_image
  
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :styles#,      :only => [:create, :destroy, :get]
  resources :term_groups#, :only => [:create, :destroy, :get]
  resources :terms#,       :only => [:create, :destroy]

  root :to => 'pages#home'

end

app/controllers/master_data_controller.rb
class MasterDataController < ApplicationController
  def show_styles
    @title  = page_title
    @style  = nil
    @styles = MasterStyle.all
    @target_term_group_id = params[:target_term_group_id]
    #puts "Our term group is #{@target_term_group_id}"
  end

  def show_federations
    @title        = page_title
    @style        = MasterStyle.find(params[:master_style_id])
    @styles       = MasterStyle.all
    @federations  = @style.master_federations
    @target_term_group_id = params[:target_term_group_id]
    
    respond_to do |format|
      format.html ##{ redirect_to @federations }
      format.js
    end
  end

  def show_term_groups
    @title        = page_title
    @style        = MasterStyle.find(params[:master_style_id])
    @styles       = MasterStyle.all
    @target_term_group_id = params[:target_term_group_id]

    @federations  = @style.master_federations
    @federation   = MasterFederation.find(params[:master_federation_id])
    @term_groups  = @federation.master_term_groups
    
    respond_to do |format|
      format.html ##{ redirect_to @federations }
      format.js
    end
  end

  def show_terms
    @title        = page_title
    @style        = MasterStyle.find(params[:master_style_id])
    @styles       = MasterStyle.all
    @target_term_group_id = params[:target_term_group_id]

    @federations  = @style.master_federations
    @federation   = MasterFederation.find(params[:master_federation_id])
    @term_group   = MasterTermGroup.find(params[:master_term_group_id])
    @term_groups  = @federation.master_term_groups
    @terms        = @term_group.master_terms
    
    respond_to do |format|
      format.html ##{ redirect_to @federations }
      format.js
    end
  end
  
  def copy_terms
    @terms = MasterTerm.find(params[:terms][:id])
    term_group = TermGroup.find(params[:target_term_group_id])

    @terms.each do |term|
      puts term.term
      new_term = Term.new
      new_term.term = term.term
      new_term.term_translated = term.term_translated
      new_term.description = term.description
      new_term.term_group = term_group
      new_term.save!
    end
    
    redirect_to :controller => 'studios', :action => 'show', :id => term_group.style.studio.id, :style_id => term_group.style.id
  end
  
  private
    def page_title
      "Styles Template"
    end
end

app/helpers/master_data_helper.rb
module MasterDataHelper
end

app/views/master_data/_choose_federation.html.erb
<%= form_tag(master_data_show_term_groups_path, :method=>'get', :remote => :true) do %>
   <%= hidden_field_tag :target_term_group_id, @target_term_group_id %>
   <%= hidden_field_tag :master_style_id, @style.id %>
   <%= select_tag "master_federation_id", options_for_select(@federations.collect { |s| [s.name, s.id] }, @federation.nil? ? nil : @federation.id) %>
   <%= submit_tag "Choose a Federation" %>
<% end -%>

app/views/master_data/_choose_style.html.erb
<%= form_tag(master_data_show_federations_path, :method=>'get', :remote => :true) do %>
   <%= hidden_field_tag :target_term_group_id, @target_term_group_id %>
   <%= select_tag "master_style_id", 
         options_for_select(@styles.collect { |s| [s.name, s.id] }, @style.nil? ? nil : @style.id),
         { :prompt => "Select a Style" } %>
   
   <%= submit_tag "Choose a Style" %>
<% end -%>

app/views/master_data/_choose_term_group.html.erb
<%= form_tag(master_data_show_terms_path, :method=>'get', :remote => :true) do %>
   <%= hidden_field_tag :target_term_group_id, @target_term_group_id %>
   <%= hidden_field_tag :master_style_id, @style.id %>
   <%= hidden_field_tag :master_federation_id, @federation.id %>
   <%= select_tag "master_term_group_id", options_for_select(@term_groups.collect { |s| [s.name, s.id] }, @term_group.nil? ? nil : @term_group.id) %>
   <%= submit_tag "Choose a Group of Terms" %>
<% end -%>

app/views/master_data/_choose_terms.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    $(function() {
      $('user_rating_positve').click(function() {
        $('some_div').show();
      }
    });
  </script>
<% end %>

<%= form_tag(master_data_copy_terms_path, :method=>'get', :name => 'terms_form') do %>

   <%= link_to_function 'Check All', "$('input:checkbox').each(function(box){$(this).attr('checked', true);})" %>
   &nbsp;&nbsp;&nbsp;
   <%= link_to_function 'Uncheck All', "$('input:checkbox').each(function(box){$(this).attr('checked', false);})" %>
   <br />
   <%= hidden_field_tag :target_term_group_id, @target_term_group_id %>
   <%= hidden_field_tag :master_style_id, @style.id %>
   <%= hidden_field_tag :master_federation_id, @federation.id %>
   <% @terms.each do |term| %>
   
      <%= check_box_tag "terms[id][]", term.id %>
      <%= term.term %>
      <% unless term.term_translated.nil? %>
         ==&gt;
         <%= term.term_translated %>
      <% end %>
      <br/>
   <% end -%>
   <%= submit_tag "Add checked terms to my style"%>
<% end -%>

app/views/master_data/show_federations.html.erb
render('choose_federation')

app/views/master_data/show_federations.js.erb
$("#master_data").html("<%= escape_javascript(render('choose_style')) %><%= escape_javascript(render('choose_federation')) %>")

app/views/master_data/show_styles.html.erb
<div id="master_data">

   <%= render('choose_style') %>
   
</div>

app/views/master_data/show_term_groups.html.erb
<%= render('choose_style') %>
<%= render('choose_federation') %>
<%= render('choose_term_group') %>

app/views/master_data/show_term_groups.js.erb
$("#master_data").html("<%= escape_javascript(render('choose_style')) %><%= escape_javascript(render('choose_federation')) %><%= escape_javascript(render('choose_term_group')) %>")

app/views/master_data/show_terms.html.erb
<%= render('choose_style') %>
<%= render('choose_federation') %>
<%= render('choose_term_group') %>
<%= render('choose_terms') %>

app/views/master_data/show_terms.js.erb
$("#master_data").html("<%= escape_javascript(render('choose_style')) %><%= escape_javascript(render('choose_federation')) %><%= escape_javascript(render('choose_term_group')) %><%= escape_javascript(render('choose_terms')) %>")