config/routes.rb
StudioSite::Application.routes.draw do
  get "term_library/show_styles"

  get "term_library/show_federations"

  get "term_library/show_term_groups"

  get "term_library/show_terms"

  get "web_services/studios"
  get "web_services/studio"
  get "web_services/events"
  get "web_services/repeating_events"
  get "web_services/terminology"

  match '/events/choose',  :to => 'events#choose'

  resources :repeating_events
  resources :events

  get "calendar/index"

  get "master_data/show_styles"
  get "master_data/show_federations"
  get "master_data/show_term_groups"
  get "master_data/show_terms"
  get "master_data/copy_terms"
  
  resources :master_data

  get "sessions/new"
  
  match ':controller/:action/:id.:format'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  match '/signup',  :to => 'studios#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  resources :studios
  match '/studio_images/:id', :to => 'studios#image', :as => :studio_image
  match '/term_images/:id', :to => 'terms#image', :as => :term_image
  
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :styles#,      :only => [:create, :destroy, :get]
  resources :term_groups#, :only => [:create, :destroy, :get]
  resources :terms#,       :only => [:create, :destroy]

  root :to => 'pages#home'

end

app/controllers/term_library_controller.rb
class TermLibraryController < ApplicationController
  def show_styles
    do_it
  end

  def show_federations
    do_it
  end

  def show_term_groups
    do_it
  end

  def show_terms
    do_it
  end
  
  private 
    def do_it
      @styles = MasterStyle.all
      @master_style_id = nil
      @master_federation_id = nil
      @master_term_group_id = nil
      @federation = nil

      if not params[:master_style_id].nil?
        @master_style_id = params[:master_style_id]
      elsif not params[:master_federation_id].nil?
        @federation = MasterFederation.find(params[:master_federation_id])
        @master_style_id = @federation.master_style_id
      elsif not params[:master_term_group_id].nil?
        @term_group = MasterTermGroup.find(params[:master_term_group_id])
        @federation = @term_group.master_federation
        @master_style_id = @federation.master_style_id
      end
      
      if not @master_style_id.nil?
        @style = MasterStyle.find(@master_style_id)
      end

      if not @style.nil? 
        @federations = @style.master_federations
      end
      
      if not @federation.nil?
        @master_federation_id = @federation.id
        @term_groups = MasterTermGroup.find(:all, :conditions => ["master_federation_id = ?", @federation.id])
      end
      
      if not @term_group.nil?
        @master_term_group_id = @term_group.id
        @terms = @term_group.master_terms
      end
    end
end

app/helpers/term_library_helper.rb
module TermLibraryHelper
end

app/views/term_library/_federation.html.erb
<li>
   <%= link_to federation.name, term_library_show_term_groups_path(:master_federation_id => federation.id), :remote => true %>
   <span id="federation_<%= federation.id %>">
      <% if federation.id.to_i == @master_federation_id.to_i %>
         <%= render :partial => 'term_library/term_groups' %>
      <% end %>
   </span>
</li>

app/views/term_library/_federations.html.erb
<ul class="federations">
  <%= render :partial => 'term_library/federation', :collection => @federations, :as => :federation %>
</ul>

app/views/term_library/_style.html.erb
<li>
   <%= link_to style.name, term_library_show_federations_path(:master_style_id => style.id), :remote => true %>
   &nbsp;&nbsp;&nbsp;&nbsp;
   <span id="style_<%= style.id %>">
     <% if style.id == @master_style_id.to_i %>
         <%= render :partial => 'term_library/federations' %>
     <% end %>
   </span>
</li>

app/views/term_library/_styles.html.erb
<h1>PARTIAL STYLES</h1>

<ul class="styles">
   <%= render :partial => 'term_library/style', :collection => @styles, :as => :style %>
</ul>

app/views/term_library/_term.html.erb
<li>
<%= term.term %>   
<% unless term.term_translated.nil? %>
   <span style="color:#a0a0a0;">translates to </span>
   <%= term.term_translated %>   
   
<% end %>

</li>

app/views/term_library/_term_group.html.erb
<li>
   <%= link_to term_group.name, term_library_show_terms_path(:master_term_group_id => term_group.id), :remote => true %>
   
   <span id="term_group_<%= term_group.id %>">
      <% if term_group.id.to_i == @master_term_group_id.to_i %>
         <%= render :partial => 'term_library/terms' %>
      <% end %>
   </span>

</li>

app/views/term_library/_term_groups.html.erb
<ul class="term_groups">
   <%= render :partial => 'term_library/term_group', :collection => @term_groups, :as => :term_group %>
</ul>

app/views/term_library/show_federations.html.erb
<%= render :partial => 'term_library/styles' %>

app/views/term_library/show_federations.js.erb
$("#style_<%= @master_style_id %>").html("<%= escape_javascript(render('term_library/federations')) %>");
$("#style_<%= @master_style_id %>").effect("highlight", {color: "#88ff88"}, 2000);
$("#style_<%= @master_style_id %>").effect("bounce", { times:3 }, 300);

app/views/term_library/show_styles.html.erb
<%= render :partial => 'term_library/styles' %>

app/views/term_library/show_term_groups.html.erb
<%= render :partial => 'term_library/styles' %>

app/views/term_library/show_term_groups.js.erb
$("#federation_<%= @master_federation_id %>").html("<%= escape_javascript(render('term_library/term_groups')) %>")

app/views/term_library/show_terms.html.erb
<%= render :partial => 'term_library/styles' %>

app/views/term_library/show_terms.js.erb
$("#term_group_<%= @master_term_group_id %>").html("<%= escape_javascript(render('term_library/terms')) %>")