config/routes.rb
StudioSite::Application.routes.draw do
  get "term_library/show_styles"

  get "term_library/show_federations"

  get "term_library/show_term_groups"

  get "term_library/show_terms"

  get "web_services/studios"
  get "web_services/studio"
  get "web_services/events"
  get "web_services/repeating_events"
  get "web_services/terminology"

  match '/events/choose',  :to => 'events#choose'

  resources :repeating_events
  resources :events

  get "calendar/index"

  get "master_data/show_styles"
  get "master_data/show_federations"
  get "master_data/show_term_groups"
  get "master_data/show_terms"
  get "master_data/copy_terms"
  
  resources :master_data

  get "sessions/new"
  
  match ':controller/:action/:id.:format'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  match '/signup',  :to => 'studios#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  resources :studios
  match '/studio_images/:id', :to => 'studios#image', :as => :studio_image
  match '/term_images/:id', :to => 'terms#image', :as => :term_image
  
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :styles#,      :only => [:create, :destroy, :get]
  resources :term_groups#, :only => [:create, :destroy, :get]
  resources :terms#,       :only => [:create, :destroy]

  root :to => 'pages#home'

end

app/models/studio.rb
require 'digest'

class Studio < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :password, :password_confirmation
  attr_accessible :name, :email, :address, :address2, :city, :state, :postal_code, :telephone, :fax
  attr_accessible :time_zone
  
  has_many :styles, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :repeating_events, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, 
            :presence   => true,
            :length     => { :maximum => 50 }
                      
  validates :email, 
            :presence   => true,
            :format     => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }

  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }


   before_save :encrypt_password

   def has_password?(submitted_password)
     encrypted_password == encrypt(submitted_password)
   end
   
   def self.authenticate(email, submitted_password)
     user = find_by_email(email)
     return nil   if user.nil?
     return user  if user.has_password?(submitted_password)
   end
   
   def self.authenticate_with_salt(id, cookie_salt)
    studio = find_by_id(id)
    (studio && studio.salt == cookie_salt) ? studio : nil
   end


   def uploaded_file=(incoming_file)
     if not incoming_file.nil?
       self.filename = incoming_file.original_filename
       self.content_type = incoming_file.content_type
       self.data = incoming_file.read
     end
   end

   def filename=(new_filename)
       write_attribute("filename", sanitize_filename("#{self.id}_#{new_filename}"))
   end

   private
     def sanitize_filename(filename)
         #get only the filename, not the whole path (from IE)
         just_filename = File.basename(filename)
         #replace all non-alphanumeric, underscore or periods with underscores
         just_filename.gsub(/[^\w\.\-]/, '_')
     end

     def encrypt_password
       self.salt = make_salt unless has_password?(password)
       self.encrypted_password = encrypt(password)
     end

     def encrypt(string)
       secure_hash("#{salt}--#{string}")
     end

     def make_salt
       secure_hash("#{Time.now.utc}--#{password}")
     end

     def secure_hash(string)
       Digest::SHA2.hexdigest(string)
     end
end
# == Schema Information
#
# Table name: studios
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  address            :string(255)
#  address2           :string(255)
#  city               :string(255)
#  state              :string(255)
#  postal_code        :string(255)
#  telephone          :string(255)
#  fax                :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#  time_zone          :string(255)
#

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_filter :authenticate,  :only => [:index, :edit, :update]
  before_filter :correct_user,  :only => [:edit, :update]
  before_filter :admin_user,    :only => :destroy

  def new
    @studio = Studio.new
    @title = signup_form_name
  end
  
  def index
    @studios = Studio.paginate(:page => params[:page])
    @title = "All Studios"
  end
  
  def show
    @studio = Studio.find(params[:id])
    @title = @studio.name
    @new_style = Style.new
    @new_term_group = TermGroup.new
    @new_term = Term.new
    
    if params[:style_id].nil?
      style = @studio.styles.first
      unless style.nil?
        style_id = style.id
      end
    else
      style_id = params[:style_id]
    end

    @current_style = Style.find(:first, :conditions => ["id = ? and studio_id = ?", style_id, params[:id]])
    @term_groups = @current_style.term_groups unless @current_style.nil?
    
    set_the_current_style_id(@current_style)
    current_studio
    
  end
  
  def create
    @studio = Studio.new(params[:studio])
    if @studio.save
      sign_in @studio
      flash[:success] = "Welcome and thanks for signing up!"
      redirect_to @studio
    else
      @title = signup_form_name
      render 'new'
    end
  end
  
  def edit
    @title = "Edit Studio"
  end
  
  def image
    studio = Studio.find(params[:id])
    send_data studio.data, :type => studio.content_type,:disposition => 'inline'
  end
  
  def update
    @studio = Studio.find(params[:id])
    
    @studio.uploaded_file = params[:studio][:image]
    
    @studio.name        = params[:studio][:name]
    @studio.password    = params[:studio][:password]
    @studio.email       = params[:studio][:email]
    @studio.address     = params[:studio][:address]
    @studio.address2    = params[:studio][:address2]
    @studio.city        = params[:studio][:city]
    @studio.state       = params[:studio][:state]
    @studio.postal_code = params[:studio][:postal_code]
    @studio.telephone   = params[:studio][:telephone]
    @studio.fax         = params[:studio][:fax]
    
    if @studio.save
      flash[:success] = "Profile updated."
      redirect_to @studio
    else
      flash[:error] = "Profile could not be updated."
      @title = "Edit studio"
      render 'edit'
    end
  end
  
  def destroy
    Studio.find(params[:id]).destroy
    flash[:success] = "Studio destroyed."
    redirect_to studios_path
  end
  
  private
  
    def signup_form_name
      "Sign Up"
    end
    
    def correct_user
      @studio = Studio.find(params[:id])
      redirect_to(root_path) unless current_studio?(@studio)
    end
    
    def admin_user
      if current_studio.nil? or not current_studio.admin?
        redirect_to(signin_path) 
      end
    end
end

app/helpers/studios_helper.rb
module StudiosHelper
  def gravatar_for(studio, options = { :size => 50 })
    gravatar_image_tag(studio.email.downcase, :alt => h(studio.name),
                                              :class => 'gravatar',
                                              :gravatar => options)
  end
  
  def can_edit_studio
    current_studio?(@studio)
  end
end

app/views/studios/_studio.html.erb
    <li>
      <%= gravatar_for studio, :size => 30 %>
      <%= link_to studio.name, studio %>

      <% if current_studio.admin? %>
      | <%= link_to "delete", 
            studio, 
            :method => :delete, 
            :confirm => "Are you sure you want to delete '#{studio.name}'?",
            :title => "Delete #{studio.name}" %>
      <% end %>

    </li>

app/views/studios/edit.html.erb
<h1>Edit Studio</h1>

<%= form_for(@studio) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  
  <%= field_set_tag 'Address' do %>
     <div class="field">
       <%= f.label :address, "Street" %><br />
       <%= f.text_field :address %>
     </div>
     <div class="field">
       <%= f.text_field :address2 %>
     </div>
     <div class="field">
       <%= f.label :city, "City, State, ZIP/Postal code" %><br />
       <%= f.text_field :city %>
       <%= f.text_field :state, :size => 2 %>
       <%= f.text_field :postal_code, :size => 7 %>
     </div>
  <% end %>

  <%= field_set_tag 'Contact' do %>
     <div class="field">
       <%= f.label :telephone, "Telephone" %><br />
       <%= f.text_field :telephone %>
     </div>
     <div class="field">
       <%= f.label :fax, "Fax" %><br />
       <%= f.text_field :fax %>
     </div>
  <% end %>

  <% if not @studio.filename.nil? %>
   <div class="label">
      Current image: <br />
      <%= image_tag(studio_image_path(@studio.id)) %>
   </div>
  <% end %>
  <div class="label">
   Upload an image for term:
  </div>
  <div class="field">
   <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.time_zone_select :time_zone %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @studio %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/studios/index.html.erb
<h1>All Studios</h1>

<%= will_paginate %>

<ul class="studios">
   <%= render @studios %>
</ul>

<%= will_paginate %>

app/views/studios/new.html.erb
<h1>Sign up</h1>

<%= form_for(@studio) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.time_zone_select :time_zone %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/studios/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="sidebar round">
      <strong>Name</strong> <%= @studio.name %><br />
      <strong>Zone</strong>  <%= @studio.time_zone %><br />
      <strong>URL</strong>  <%= link_to @studio.name, @studio %>
      <br/>
      <%= link_to "View Calendar", '/calendar/index' %>
      <br/>
      <% if not @studio.styles.nil? %>
         <table class="styles" summary="Studio styles">
            <tr><th>Styles</th></tr>
              <%= render @studio.styles %>
            <tr>
               <td>
                  <%= render 'shared/style_form' %>
               </td>
            </tr>
         </table>
      <% end %>
      <%= link_to "Browse Term Library", term_library_show_styles_path %>
    </td>
    <td class="main" style="vertical-align:top;">
      <h1>
         <%= gravatar_for @studio, :size => 30 %>
         <%= @studio.name %>
       </h1>
       &nbsp;<br/>
       <% unless @current_style.nil? %>
          <div class="current_style round">
          <%= @current_style.name %>
          </div>
          <br />
          <%=  %><br/>
          
          <%= link_to_if can_edit_studio, 'Add group of terms', new_term_group_path %>
          
          <%= render :partial => "term_groups/show", :collection => @term_groups, :as => :term_group %>

       <% end %>
       
       <hr size="1">

       <% if Rails.env.development? %>
          <hr size="1">
          <style type="text/css" media="screen">
            dl.event
            {
            	margin: 2em 0;
            	padding: 0;
            	font-family: georgia, times, serif;
            }

            .event dt
            {
            	position: relative;
            	left: 0;
            	top: 1.1em;
            	width: 5em;
            	font-weight: bold;
            }

            .event dd
            {
            	border-left: 1px solid #000;
            	margin: 0 0 0 6em;
            	padding: 0 0 .5em .5em;
            }
          </style>
          Calendar Item Example
          <dl class="event">
          	<dt>23 March</dt>
          	<dd>Car club meeting</dd>
          	<dd>7pm</dd>
          	<dd>See a wide range of classic cars on display... </dd>
          	<dt>13 June</dt>
          	<dd>Cake stall</dd>
          	<dd>12pm</dd>
          	<dd>Cakes of every type. All proceeds go to the... </dd>
          </dl>
      <% end %>
    </td>
  </tr>
</table>